language: node_js
services:
- docker
node_js:
- '11'
cache: npm
filter_secrets: false
before_deploy:
- git config --local user.name "Manuel-777"
- git config --local user.email "manuel.etchegaray7@gmail.com"
jobs:
  include:
  - stage: Test
    os: linux
    dist: xenial
    sudo: required
    script:
    - npm run test
  - stage: Build
    os: linux
    dist: xenial
    sudo: required
    script:
    - npm run start
    deploy:
      provider: releases
      file_glob: true
      skip_cleanup: true
      prerelease: true
      draft: false
      api_key:
        secure: nK/FjVb2J1lGhlILkf78OMEiVlKtrpO1mRMtc+OvqzOZIc9a/E+CXCrwxQ13Pwd9/qYXN/tijOUq1EBavxu//JuLyvebLjho51Acu+EQpr8Z7OFZkyuU/V8NnvHDY0MVV86lAtuuSleyeqP+/qDJOrDnr/6K5z2RBQP3JloUcKqTQXa9QqJnxAPMocguYVmSLo9X2gpShbs901PDclZuAhgoT+5nAtnIMWo8qJMDD7DOF00QYnOKj68uCn6D80fxYVyFApDLYZMeSPgkgESZpsbKuWchNO+bgifWsgDZGNY3f3KCJe1+QUcxoACvj0JywBRkVXqbi4LbOTyeWU3xx5PZ2Zx7me6+potZqseowY4Rez0H//xFtefDAXVbbr78LzRJHdIZqOcVuZymN2x/NoLZnnEPIdhVBD1+8zgp6EJb+Flvz38aDFUUF86iKBr3wW89xgYnso46mYRc3Wjq6qPCpllnBMR6Kh2zRlbovh+c+RERJDOMvOci5OV9MJwKrx+5qiKAbBHJq04oqdIpgaPKnp/HVeDL3DOXkppWQQGXw3BPpXGU5DryWe3r3xqQ1VDmL/kYOSXurBurBGlGQIOoXloyjBX05HCLQszWvKBod0W0F1gEGLd4jLOlQqVv15UszH19n0XJkC6kEt8GlpANj1QOO0ytGcdK5gcPTkE=
      file: dist/*
      on:
        tags: true
        repo: Manuel-777/MTG-Arena-Tool-Metadata
