language: node_js

services:
  - docker

node_js:
  - '11'

cache: npm

filter_secrets: false

before_deploy:
  - git config --local user.name "Manuel-777"
  - git config --local user.email "manuel.etchegaray7@gmail.com"

jobs:
  include:
    - stage: Build
      os: linux
      dist: xenial
      sudo: required
      script:
        - npm run start
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        prerelease: true
        draft: false
        api_key:
          secure: 
        file: dist/*
        on:
          tags: true
          repo: Manuel-777/MTG-Arena-Tool-Metadata