language: node_js

services:
  - docker

node_js:
  - '11'

cache: npm

filter_secrets: false

before_deploy:
  - git config --local user.name "Manuel-777"
  - git config --local user.email "manuel.etchegaray7@gmail.com"

jobs:
  include:
    - stage: Test
      os: linux
      env: YARN_GPG=no
      script:
        - npm run breaking
          on:
            commit_message: push breaking
        - npm run feature
          on:
            commit_message: push feature
        - npm run fix
          on:
            commit_message: push fix
    - stage: Build
      os: linux
      dist: xenial
      sudo: required
      script:
        - npm run start
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        prerelease: true
        draft: false
        api_key:
          secure: qE/6ytyZtzLbBxW189kdb1yDGMzmxoRBeq4MKIic/YlGjd6w8PM7i3KDBLyytL+DGUXUGUaxaAXrnwNNBVvKlAg9Qhn5E5Dy3d+izrtQM61zv27eGFQLNpUdHcY6hlUcQYbWGrn9YI82r9B3tSB6vssw8kV0EqmPTdqfXyQpL/7/Fbwb1E5dZ7Opyo8Xmu3W/3DjlJToQUW8c4qgq9Pwk3qYlfbSSc/Dpygovg7IGYAaKgBfO+fsqU8t2TDJA++DPzbzGzn6mX/Q3DsZ/a8VsmJlxZTWyvgfwitjHlDUMGknMfqMbdAAcR0dJdZrU8lOFC9I8Z1+gZuX00ocAukC0ACAqxXZc1Sl+vOT+dfO26qIWK03lKsQBCCLezAZA9UhU+5cwWFdXXbEjQG0vdlwQblPysoQID51yVkPGtX4GycKdCfSN0Wx9CwBBo7DQI1X/BXGFQVjQiVlMtz5SIr08JHVs954qhSw0ZNOpF6uHvjXqlBrlNkix5+GXCN9r2auiKQaKTnrmjTugtLBRAGrdiyT9QA2XK0p8UPCqVbLpAH1NbY2vdJoaWpQYhjtE3RfBc/gw9pcwmsJCttdDlYHhrV3pxSAd2ZN5OrJbKHuKL5hF+dPDPwJ7vTWXE2lY+nJ3tvVzX7e3OOuHS8FnYuScXqvIBgTwEk8hqVJ8d1jMuY=
        file: dist/*
        on:
          tags: true
          repo: Manuel-777/MTG-Arena-Tool-Metadata
      after_success:
        - npm run dist
