language: node_js

services:
  - docker

node_js:
  - '11'

cache: npm

filter_secrets: false

before_deploy:
  - git config --local user.name "Manuel-777"
  - git config --local user.email "manuel.etchegaray7@gmail.com"

  jobs:
  include:
    - stage: Test
      os: linux
      dist: xenial
      script:
        - npm run test
    - stage: Build
      os: linux
      dist: xenial
      sudo: required
      script:
        - npm run start
      deploy:
        provider: releases
        overwrite: true
        file_glob: true
        skip_cleanup: true
        prerelease: true
        draft: false
        api_key:
          secure: nVeU/YgUjCgmGDoEwxWvdux5LoAhr8mx3rsQ87FujdtooVB3jJGLuaLFN3RuJHPDqlbzkJ443ZvhBjIF5mbjXoJhJjsey7dxNZrCgtT3g022as+8RTV54r4yfTXocTzSvE/wOl2PTcAASs+8vNem9H25eVr20AATAqvhLPho7t1aFV3/YHk+aNzvPbp8NEIN8kRrGOQCEycgCI0Sm+ol2aprUuWi9MeXLMvp3STG6v083FpoEGNiG8iWfNTNH/vqETdM9AAvv/Z7+K3EETzoVKJnC8OScTFjhibI8Fk1Dl5pvLecAQDL/a/y0j7N7NwIgLI04SO2Ajq/Wl66EYehDa5BiZbTkj59EAKg4j7yIWMQNGREPgetwmIbU37s35LfH0T5+1PogkzS7c/zcQRjLFay0eiXLqrIltK/kLvSqq8oqR1gnL86aZdwuJ/N9ovo8TlWK8W4+uKwrwJVrIe35rTD/1ooqXC03t0QAUq+FnJJZhJP8xcZdlVxT2QA6075vvJoLyaAnS92xbuBvFwaKVRjJhU79iRkyeHfagLS3w/t/bStf3zD4M2E7eaXAw9UIEbMzEaMbbQ0cRv0WlU9bl3Jl9FjhnCkdY3a+jsmk8y1eMQuOKoOVFWbPDdpOq0FiXtl0C+siho3DIitf0TkHy1trwfYvXypjdfdDCeVszw=
        file: dist/*
        on:
          tags: true
          repo: Manuel-777/MTG-Arena-Tool-Metadata
      after_success:
        - npm run dist
