language: node_js
services:
- docker
node_js:
- '11'
cache: npm
filter_secrets: false
before_deploy:
- git config --local user.name "Manuel-777"
- git config --local user.email "manuel.etchegaray7@gmail.com"
jobs:
  include:
  - stage: Test
    os: linux
    dist: xenial
    sudo: required
    script:
      - npm run test
  - stage: Build
    os: linux
    dist: xenial
    sudo: required
    script:
      - npm run start
      - npm run dist
      on:
        tags: true

